---
title: "CourseProject"
author: "wpmcdonald"
date: "August 22, 2014"
output: html_document
---
##Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geek. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

The goal of your project is to predict the manner in which they did the exercise.
The five classes we are having to predict are:  
1. **A** Exact bicep curl
2. **B** Throwing elbows to the front
3. **C** Lifting the dumbbell only halfway
4. **D** Lowering the dumbbell only halfway
5. **E** Throwing the hip forward

## Summary

Six male participants aged between 20-28 years, were asked to perform one set of 10 repetitions
of the Unilateral Dumbbell Biceps Curl in five different ways [Velloso, E. _et al._, 2013].
Correctly according to a specification (Class **A**) and with a set of common mistakes: throwing
the elbows to the front (Class **B**), lifting the dumbbell only halfway (Class **C**), lowering
the dumbbell only halfway (Class **D**) and throwing the hips to the front (Class **E**). The goal
of this project is to use data from wearable sensors mounted in the user's glove, armband, lumbar
belt and dumbbell in order to build a machine learning algorithm to predict the manner in which
they did exercise (outcome: **_classe_**) and therefore access the quality of the exercise.  

The data for this project and the original paper describing the experiment are available
[here](http://groupware.les.inf.puc-rio.br/har).


```{r dataPartition, echo=TRUE, tidy=TRUE}
library(caret, quietly = TRUE)
set.seed(1234)

pml_training <- read.csv("pml-training.csv", na.strings=c("NA", "#DIV/0!"))
dim(pml_training)
inTrain <- createDataPartition(y=pml_training$classe, p=0.7, list=FALSE)
training <- pml_training[inTrain,]
validation <- pml_training[-inTrain,]
dim(training)
``` 
